### ISSUE TITLE
Light wallet shows incorrect sync progress

### ISSUE THREAD

**Issue by yghazi** [energicryptocurrency/energi#270] opened 2018-05-14 08:08 UTC
Not sure if this issue is a duplicate, but when the wallet is run without DAG then the progress bar doesn't update until all the headers are synced and even then doesn't show the correct progress. Likely because the `UpdateTip` shows incorrect progress: 
```
2018-05-14 08:04:38 UpdateTip: new best=06a98ed7e00ef904e82b5e28d03567174d67da2a74215afdb3a6f7447ab562b3  height=16386  log2_work=51.400641  tx=16641  date=2018-04-26 13:53:39 progress=1.000000  cache=3.8MiB(16586tx)
```
Note: this is using the latest build found on the energi website.

**Comment by RyanLucchese** [comment] 2018-06-22 18:35
Duplicate of Issue #222

**Closed by RyanLucchese** 2018-06-22 18:35 UTC
